name: 功能请求
about: 建议一个新功能或对现有功能的改进
title: "[Feature] 简短描述"
labels: enhancement
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能请求！您的建议对我们改进 JadeView 非常重要。

  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请清晰、详细地描述您建议的功能或改进。
      placeholder: 例如：我希望 JadeView 支持更多的背景材料效果，如 Aero Glass。
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 动机和使用场景
      description: 请描述为什么需要这个功能，以及您在什么情况下会使用它。
      placeholder: |
        动机：当前的背景材料效果有限，无法满足某些设计需求。
        使用场景：当我创建现代化的桌面应用时，希望能够使用更多样化的背景效果。
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 建议的实现方式
      description: 如果您有建议的实现方式，请在这里描述。
      placeholder: |
        1. 扩展背景材料的枚举类型，添加新的背景效果
        2. 在 Rust 代码中实现新的背景效果
        3. 更新 C API 和易语言封装
        4. 添加相关的文档和示例

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 请描述您考虑过的任何替代方案。
      placeholder: 例如：我尝试过使用自定义 CSS 样式来模拟背景效果，但效果不理想。

  - type: textarea
    id: additional-context
    attributes:
      label: 附加信息
      description: 请提供任何其他可能有助于理解这个功能请求的信息，例如截图、示例代码或参考链接。
      placeholder: |
        参考链接：
        - https://docs.microsoft.com/en-us/windows/apps/design/style/mica
        - https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/Materials/BackgroundMaterial.cpp

  - type: checkboxes
    id: checkboxes
    attributes:
      label: 检查项
      description: 在提交之前，请确保您已经完成了以下检查：
      options:
        - label: 我已经查看了现有的 Issues，确保没有重复请求
          required: true
        - label: 我已经提供了清晰、详细的功能描述
          required: true
        - label: 我已经说明了这个功能的动机和使用场景
          required: true