name: Feature Request
description: Suggest a new feature
title: "[Feature] "
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting this feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: I'd like to see...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you need this feature?
      placeholder: This feature would help me...
    validations:
      required: true

  - type: textarea
    id: suggested-implementation
    attributes:
      label: Suggested Implementation
      description: How would you implement this feature?
      placeholder: Maybe we could...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: I tried...