name: Question
description: Ask a question about using JadeView
title: "[Question] "
labels:
  - question

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question!

  - type: textarea
    id: what-you-need
    attributes:
      label: What do you need help with?
      description: Describe your question in detail
      placeholder: I need help with...
    validations:
      required: true

  - type: textarea
    id: what-you-tried
    attributes:
      label: What have you tried so far?
      description: Describe what you've already tried
      placeholder: I've tried...

  - type: textarea
    id: code-examples
    attributes:
      label: Code examples
      description: Share any relevant code examples
      placeholder: ```c
        // Your code here
        ```

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      placeholder: |
        - OS: Windows 10
        - JadeView Version: v1.1.0
        - Language: C / E Language
        - Compiler: MSVC 2022 / E Language 5.91