#ifndef JADEVIEW_H
#define JADEVIEW_H

/* Autogenerated header file for JadeView DLL - 自动生成的头文件 */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

#ifdef __cplusplus
extern "C" {
#endif

// 基本类型定义
typedef int32_t i32;
typedef uint32_t u32;
typedef char c_char;

// 结构体定义
struct RGBA {
    i32 r;
    i32 g;
    i32 b;
    i32 a;
};

struct WebViewSettings {
    i32 autoplay;
    i32 background_throttling;
    i32 disable_right_click;
    const c_char* ua;
    const c_char* preload_js;
    i32 allow_fullscreen;
    const c_char* postmessage_whitelist;
};

struct WebViewWindowOptions {
    const c_char* title;
    i32 width;
    i32 height;
    i32 resizable;
    i32 remove_titlebar;
    i32 transparent;
    struct RGBA background_color;
    i32 always_on_top;
    i32 no_center;
    const c_char* theme;
    i32 maximized;
    i32 maximizable;
    i32 minimizable;
    i32 x;
    i32 y;
    i32 min_width;
    i32 min_height;
    i32 max_width;
    i32 max_height;
    i32 fullscreen;
    i32 focus;
    i32 hide_window;
    i32 use_page_icon;
    i32 borderless;
};

// IPC回调函数类型
typedef void (*IpcCallback)(u32, const c_char*);

// 函数声明
extern "system" i32 JadeView_init(i32 enable_devtools, const c_char* log_path, const c_char* data_directory);
extern "system" i32 run_message_loop();
extern "system" u32 create_webview_window(
    const c_char* url,
    u32 parent_window_id,
    const struct WebViewWindowOptions* options,
    const struct WebViewSettings* webview_settings
);
extern "system" i32 navigate_to_url(u32 window_id, const c_char* url);
extern "system" i32 reload_webview_window(u32 window_id);
extern "system" i32 execute_javascript(u32 window_id, const c_char* script);
extern "system" i32 set_window_title(u32 window_id, const c_char* title);
extern "system" i32 set_window_size(u32 window_id, i32 width, i32 height);
extern "system" i32 set_window_position(u32 window_id, i32 x, i32 y);
extern "system" i32 set_window_visible(u32 window_id, i32 visible);
extern "system" i32 set_window_focus(u32 window_id);
extern "system" i32 set_window_always_on_top(u32 window_id, i32 always_on_top);
extern "system" i32 close_window(u32 window_id);
extern "system" i32 minimize_window(u32 window_id);
extern "system" i32 toggle_maximize_window(u32 window_id);
extern "system" i32 is_window_maximized(u32 window_id);
extern "system" u32 get_window_count();
extern "system" u32 jade_on(const c_char* event_name, IpcCallback callback);
extern "system" i32 jade_off(const c_char* event_name, u32 callback_id);
extern "system" i32 register_ipc_handler(const c_char* channel, IpcCallback ipc_cb);
extern "system" i32 set_window_theme(u32 window_id, const c_char* theme);
extern "system" i32 set_window_enabled(u32 window_id, i32 enabled);
extern "system" i32 get_window_theme(u32 window_id);
extern "system" i32 create_local_server(
    const c_char* root_path,
    const c_char* appname,
    c_char* url_buffer,
    usize buffer_size
);
extern "system" i32 request_redraw(u32 window_id);
extern "system" i32 send_ipc_message(
    u32 window_id,
    const c_char* message_type,
    const c_char* message_content
);
extern "system" i32 set_window_backdrop(u32 window_id, const c_char* backdrop_type);
extern "system" i32 cleanup_all_windows();
extern "system" i32 get_webview_version(c_char* buffer, usize buffer_size);
extern "system" i32 set_window_fullscreen(u32 window_id, i32 fullscreen);
extern "system" void jade_text_free(c_char* ptr);
extern "system" c_char* jade_text_create(const c_char* text);

#ifdef __cplusplus
}
#endif

#endif // JADEVIEW_H
