#ifndef JADEVIEW_H
#define JADEVIEW_H

/* Autogenerated header file for JadeView DLL - 自动生成的头文件 */

#ifdef __cplusplus
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
extern "C" {
#else
#include <stdarg.h>
#include <stdint.h>
#include <stdlib.h>
#endif

/* ======================== 基本类型定义 ======================== */

typedef int32_t i32;
typedef uint32_t u32;
typedef char c_char;

/* ======================== 结构体定义 ======================== */

/*
 * RGBA颜色结构体
 * 用于设置窗口背景颜色
 */
struct RGBA {
    i32 r;  /* 红色通道 (0-255) */
    i32 g;  /* 绿色通道 (0-255) */
    i32 b;  /* 蓝色通道 (0-255) */
    i32 a;  /* 透明度 (0-255, 0=完全透明, 255=完全不透明) */
};

/*
 * WebView设置选项结构体
 * 用于配置WebView的高级选项
 */
struct WebViewSettings {
    i32 autoplay;               /* 是否允许自动播放媒体 (0=false, 1=true) */
    i32 background_throttling;  /* 背景限速策略 (0=默认, 1=禁用背景限速) */
    i32 disable_right_click;    /* 是否禁用页面右键菜单 (0=禁用, 1=启用) */
    const c_char* ua;           /* 自定义User-Agent字符串指针，NULL表示使用默认UA */
    const c_char* preload_js;   /* 预载JavaScript代码字符串指针，NULL表示不预载JS */
    i32 allow_fullscreen;       /* 是否允许页面全屏 (0=false, 1=true) */
    const c_char* postmessage_whitelist; /* PostMessage白名单，单个域名字符串 */
};

/*
 * WebView窗口选项结构体
 * 用于创建窗口时配置窗口属性
 */
struct WebViewWindowOptions {
    const c_char* title;        /* 窗口标题 */
    i32 width;                  /* 窗口宽度 */
    i32 height;                 /* 窗口高度 */
    i32 resizable;              /* 是否可调整大小 (0=false, 1=true) */
    i32 remove_titlebar;        /* 是否去除标题栏 (0=显示, 1=去除) */
    i32 transparent;            /* 是否透明背景 (0=false, 1=true) */
    struct RGBA background_color; /* 背景颜色 */
    i32 always_on_top;          /* 是否置顶 (0=false, 1=true) */
    i32 no_center;              /* 是否禁止居中 (0=居中, 1=不居中) */
    const c_char* theme;        /* 窗口主题 ("Light", "Dark", "System") */
    i32 maximized;              /* 是否最大化 (0=false, 1=true) */
    i32 maximizable;            /* 是否显示最大化按钮 (0=false, 1=true) */
    i32 minimizable;            /* 是否显示最小化按钮 (0=false, 1=true) */
    i32 x;                      /* 窗口X坐标 (-1=居中) */
    i32 y;                      /* 窗口Y坐标 (-1=居中) */
    i32 min_width;              /* 最小宽度 (0=不限制) */
    i32 min_height;             /* 最小高度 (0=不限制) */
    i32 max_width;              /* 最大宽度 (0=不限制) */
    i32 max_height;             /* 最大高度 (0=不限制) */
    i32 fullscreen;             /* 是否全屏 (0=false, 1=true) */
    i32 focus;                  /* 是否获取焦点 (0=false, 1=true) */
    i32 hide_window;            /* 是否隐藏窗口 (0=显示, 1=隐藏) */
    i32 use_page_icon;          /* 是否使用页面图标 (0=使用主进程图标, 1=使用页面图标) */
    i32 borderless;             /* 是否无边框 (0=有边框, 1=无边框) */
    i32 content_protection;     /* 是否启用内容保护 (0=false, 1=true) */
};

/*
 * 通知参数结构体
 * 用于显示系统通知
 */
struct NotificationParams {
    const c_char* summary;      /* 通知标题（必填） */
    const c_char* body;         /* 通知内容 */
    const c_char* icon;         /* 图标路径 */
    i32 timeout;                /* 超时时间（毫秒，默认5000） */
    const c_char* button1;      /* 第一个按钮文本 */
    const c_char* button2;      /* 第二个按钮文本 */
    const c_char* text3;        /* 第三行文本 */
    const c_char* action;       /* 动作参数 */
};

/*
 * 打开文件对话框参数结构体
 */
struct OpenDialogParams {
    u32 window_id;              /* 父窗口ID */
    const c_char* title;        /* 对话框标题 */
    const c_char* default_path; /* 默认路径 */
    const c_char* button_label; /* 按钮标签 */
    const c_char* filters;      /* 文件过滤器（JSON格式） */
    const c_char* properties;   /* 对话框属性（JSON格式） */
    i32 blocking;               /* 是否阻塞 (0=非阻塞, 1=阻塞) */
    void (*callback)(const c_char*); /* 回调函数 */
};

/*
 * 保存文件对话框参数结构体
 */
struct SaveDialogParams {
    u32 window_id;              /* 父窗口ID */
    const c_char* title;        /* 对话框标题 */
    const c_char* default_path; /* 默认路径 */
    const c_char* button_label; /* 按钮标签 */
    const c_char* filters;      /* 文件过滤器（JSON格式） */
    i32 blocking;               /* 是否阻塞 (0=非阻塞, 1=阻塞) */
    void (*callback)(const c_char*); /* 回调函数 */
};

/*
 * 消息框参数结构体
 */
struct MessageBoxParams {
    u32 window_id;              /* 父窗口ID */
    const c_char* title;        /* 消息框标题 */
    const c_char* message;      /* 消息内容 */
    const c_char* detail;       /* 详细信息 */
    const c_char* buttons;      /* 按钮文本（使用|分隔） */
    i32 default_id;             /* 默认按钮索引 (-1=无) */
    i32 cancel_id;              /* 取消按钮索引 (-1=无) */
    const c_char* type_;        /* 消息框类型 ("none", "info", "error", "warning", "question") */
    i32 blocking;               /* 是否阻塞 (0=非阻塞, 1=阻塞) */
    void (*callback)(const c_char*); /* 回调函数 */
};

/* ======================== 回调函数类型 ======================== */

/*
 * IPC回调函数类型
 * 参数: window_id - 窗口ID
 *       message - 消息内容（JSON格式字符串）
 * 返回: UTF-8字符串指针，用于invoke API
 */
typedef const c_char* (*IpcCallback)(u32 window_id, const c_char* message);

/* ======================== 核心函数声明 ======================== */

/*
 * 初始化JadeView DLL
 * 参数: enable_devtools - 是否启用开发者工具 (0=false, 1=true)
 *       log_path - 日志文件路径，NULL表示不输出日志到文件
 *       data_directory - WebView数据目录，NULL表示使用默认值
 * 返回: 1=成功, 0=失败
 */
i32 JadeView_init(i32 enable_devtools, const c_char* log_path, const c_char* data_directory);

/*
 * 运行消息循环（阻塞调用）
 * 在DLL模式下通常不需要宿主调用，因为已经spawn了线程
 * 返回: 1=成功
 */
i32 run_message_loop(void);

/*
 * 创建WebView窗口
 * 参数: url - 初始加载的URL
 *       parent_window_id - 父窗口ID，0表示无父窗口
 *       options - 窗口选项结构体指针
 *       webview_settings - WebView设置结构体指针，可为NULL
 * 返回: 窗口ID (0表示失败)
 */
u32 create_webview_window(
    const c_char* url,
    u32 parent_window_id,
    const struct WebViewWindowOptions* options,
    const struct WebViewSettings* webview_settings
);

/*
 * 导航到指定URL
 * 参数: window_id - 窗口ID
 *       url - 目标URL
 * 返回: 1=成功, 0=失败
 */
i32 navigate_to_url(u32 window_id, const c_char* url);

/*
 * 刷新WebView页面
 * 参数: window_id - 窗口ID
 * 返回: 1=成功, 0=失败
 */
i32 reload_webview_window(u32 window_id);

/*
 * 执行JavaScript代码
 * 参数: window_id - 窗口ID
 *       script - JavaScript代码
 * 返回: 请求ID，结果通过javascript-result事件返回
 */
i32 execute_javascript(u32 window_id, const c_char* script);

/*
 * 设置窗口标题
 * 参数: window_id - 窗口ID
 *       title - 标题文本
 * 返回: 1=成功, 0=失败
 */
i32 set_window_title(u32 window_id, const c_char* title);

/*
 * 设置窗口大小
 * 参数: window_id - 窗口ID
 *       width - 宽度
 *       height - 高度
 * 返回: 1=成功, 0=失败
 */
i32 set_window_size(u32 window_id, i32 width, i32 height);

/*
 * 设置窗口位置
 * 参数: window_id - 窗口ID
 *       x - X坐标
 *       y - Y坐标
 * 返回: 1=成功, 0=失败
 */
i32 set_window_position(u32 window_id, i32 x, i32 y);

/*
 * 设置窗口可见性
 * 参数: window_id - 窗口ID
 *       visible - 是否可见 (0=隐藏, 1=显示)
 * 返回: 1=成功, 0=失败
 */
i32 set_window_visible(u32 window_id, i32 visible);

/*
 * 设置窗口焦点
 * 参数: window_id - 窗口ID
 * 返回: 1=成功, 0=失败
 */
i32 set_window_focus(u32 window_id);

/*
 * 设置窗口是否置顶
 * 参数: window_id - 窗口ID
 *       always_on_top - 是否置顶 (0=false, 1=true)
 * 返回: 1=成功, 0=失败
 */
i32 set_window_always_on_top(u32 window_id, i32 always_on_top);

/*
 * 关闭窗口
 * 参数: window_id - 窗口ID
 * 返回: 1=成功, 0=失败
 */
i32 close_window(u32 window_id);

/*
 * 最小化窗口
 * 参数: window_id - 窗口ID
 * 返回: 1=成功, 0=失败
 */
i32 minimize_window(u32 window_id);

/*
 * 切换窗口最大化/还原状态
 * 参数: window_id - 窗口ID
 * 返回: 1=成功, 0=失败
 */
i32 toggle_maximize_window(u32 window_id);

/*
 * 获取窗口是否最大化
 * 参数: window_id - 窗口ID
 * 返回: 1=最大化, 0=未最大化或失败
 */
i32 is_window_maximized(u32 window_id);

/*
 * 获取窗口数量
 * 返回: 当前窗口数量
 */
u32 get_window_count(void);

/*
 * 设置窗口主题
 * 参数: window_id - 窗口ID
 *       theme - 主题名称 ("Light", "Dark", "System")
 * 返回: 1=成功, 0=失败
 */
i32 set_window_theme(u32 window_id, const c_char* theme);

/*
 * 获取窗口主题
 * 参数: window_id - 窗口ID
 * 返回: 1=Dark, 0=Light或失败
 */
i32 get_window_theme(u32 window_id);

/*
 * 启用/禁用窗口
 * 参数: window_id - 窗口ID
 *       enabled - 是否启用 (0=禁用, 1=启用)
 * 返回: 1=成功, 0=失败
 */
i32 set_window_enabled(u32 window_id, i32 enabled);

/*
 * 设置窗口全屏状态
 * 参数: window_id - 窗口ID
 *       fullscreen - 是否全屏 (0=false, 1=true)
 * 返回: 1=成功, 0=失败
 */
i32 set_window_fullscreen(u32 window_id, i32 fullscreen);

/*
 * 设置内容保护
 * 参数: window_id - 窗口ID
 *       content_protection - 是否启用 (0=false, 1=true)
 * 返回: 1=成功, 0=失败
 */
i32 set_content_protection(u32 window_id, i32 content_protection);

/*
 * 设置WebView缩放级别
 * 参数: window_id - 窗口ID
 *       level - 缩放级别 (1.0=100%)
 * 返回: 1=成功, 0=失败
 */
i32 set_webview_zoom(u32 window_id, double level);

/*
 * 请求窗口重绘
 * 参数: window_id - 窗口ID
 * 返回: 1=成功, 0=失败
 */
i32 request_redraw(u32 window_id);

/*
 * 设置窗口背景材料（仅Windows 11支持）
 * 参数: window_id - 窗口ID
 *       backdrop_type - 背景类型 ("mica", "micaAlt", "acrylic")
 * 返回: 1=成功, 0=失败
 */
i32 set_window_backdrop(u32 window_id, const c_char* backdrop_type);

/* ======================== 事件系统函数 ======================== */

/*
 * 注册事件监听器
 * 参数: event_name - 事件名称
 *       callback - 回调函数
 * 返回: 回调ID (用于注销)
 */
u32 jade_on(const c_char* event_name, IpcCallback callback);

/*
 * 注销事件监听器
 * 参数: event_name - 事件名称
 *       callback_id - 回调ID
 * 返回: 1=成功, 0=失败
 */
i32 jade_off(const c_char* event_name, u32 callback_id);

/*
 * 注册IPC消息处理器
 * 参数: channel - 通道名称
 *       ipc_cb - IPC回调函数
 * 返回: 1=成功, 0=失败
 */
i32 register_ipc_handler(const c_char* channel, IpcCallback ipc_cb);

/*
 * 发送IPC消息到前端
 * 参数: window_id - 窗口ID
 *       message_type - 消息类型
 *       message_content - 消息内容（将被释放）
 * 返回: 1=成功, 0=失败
 */
i32 send_ipc_message(
    u32 window_id,
    const c_char* message_type,
    const c_char* message_content
);

/* ======================== 对话框函数 ======================== */

/*
 * 显示打开文件对话框
 * 参数: params - 对话框参数结构体指针
 * 返回: 1=成功, 0=失败
 */
i32 jade_dialog_show_open_dialog(const struct OpenDialogParams* params);

/*
 * 显示保存文件对话框
 * 参数: params - 对话框参数结构体指针
 * 返回: 1=成功, 0=失败
 */
i32 jade_dialog_show_save_dialog(const struct SaveDialogParams* params);

/*
 * 显示消息框
 * 参数: params - 消息框参数结构体指针
 * 返回: 1=成功, 0=失败
 */
i32 jade_dialog_show_message_box(const struct MessageBoxParams* params);

/*
 * 显示错误框
 * 参数: window_id - 父窗口ID
 *       title - 错误标题
 *       content - 错误内容
 * 返回: 1=成功, 0=失败
 */
i32 jade_dialog_show_error_box(u32 window_id, const c_char* title, const c_char* content);

/* ======================== 通知函数 ======================== */

/*
 * 显示系统通知（仅Windows）
 * 参数: params - 通知参数结构体指针
 * 返回: 1=成功, 0=失败
 */
i32 show_notification(const struct NotificationParams* params);

/*
 * 注册通知应用到Windows注册表（需要管理员权限，仅Windows）
 * 参数: app_name - 应用名称
 *       icon_path - 图标路径
 * 返回: 1=成功, 0=失败
 */
i32 set_notification_app_registry(const c_char* app_name, const c_char* icon_path);

/* ======================== 本地服务器函数 ======================== */

/*
 * 创建本地服务器
 * 参数: root_path - 根目录路径
 *       appname - 应用名称
 *       url_buffer - 用于接收服务地址的缓冲区
 *       buffer_size - 缓冲区大小
 * 返回: 1=成功, 0=失败
 */
i32 create_local_server(
    const c_char* root_path,
    const c_char* appname,
    c_char* url_buffer,
    size_t buffer_size
);

/* ======================== 工具函数 ======================== */

/*
 * 清理所有窗口并结束消息循环
 * 返回: 1=成功, 0=失败
 */
i32 cleanup_all_windows(void);

/*
 * 获取WebView版本号
 * 参数: buffer - 用于接收版本号的缓冲区
 *       buffer_size - 缓冲区大小
 * 返回: 1=成功, 0=失败
 */
i32 get_webview_version(c_char* buffer, size_t buffer_size);

/*
 * 检查当前系统是否为Windows 11
 * 返回: 1=是Windows 11, 0=不是
 */
i32 is_windows_11(void);

/*
 * 释放JadeView分配的字符串内存
 * 参数: ptr - 要释放的指针
 */
void jade_text_free(c_char* ptr);

/*
 * 创建JadeView字符串（分配内存）
 * 参数: text - 源文本
 * 返回: 分配的字符串指针，使用完毕后需调用jade_text_free释放
 */
c_char* jade_text_create(const c_char* text);

#ifdef __cplusplus
}
#endif

#endif /* JADEVIEW_H */
